stages:
  - mon_test

job:mon_test:
  stage: mon_test
  image: python:3.6
  script:
    - apt-get update -qy
    - sh install.sh
    - python3 ./resolution_coreferences_pronominales/__main__.py
    - for f in resolution_coreferences_pronominales/tests/*.py; do python "$f"; done
    - sh uninstall.sh



